### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by FinMan28** [liren2515/GarmentRecovery#1]
Hello,
i tried to install the library and when i got to "python fit_jacket.py" i encountered this error: "FileNotFoundError: [Errno 2] No such file or directory: '/scratch/cvlab/home/ren/code/cloth-from-image/extra-data/parts14_vertex_idx.pkl'" It looks like some kind of absolute path, do you know how to fix this problem?
I am eager for you response. Thanks a lot!
![Capture](https://github.com/liren2515/GarmentRecovery/assets/62594588/eb2fee83-c66a-4725-9852-1286426d6209)

**Comment by liren2515** [comment]
I made a modification. Please git pull again.

**Comment by FinMan28** [comment]
Thank you for your help, that solved the issue :)
