### ISSUE TITLE
Prepare for the training dataset

### ISSUE THREAD

**Issue by LSQsjtu** [liren2515/GarmentRecovery#2]
Congratulations on your fantastic work!

I was wondering if you have any plans to open-source the training dataset or provide the code pipeline for preparing the training data. 

Thank you once again for your amazing contributions!

**Comment by liren2515** [comment]
Sorry, we don't plan to release the training data. I may provide the code for cutting and flattening the garment at a later time if I have time.

**Comment by LSQsjtu** [comment]
Thank you for the reply! I'm looking forward to the code being released. The tools you've developed sound incredibly useful, and having access to them would be greatly appreciated by the community.
